server:
  port: 8091

springfox:
  title: 'FINT SSE Adapter Skeleton'
  version: '@version@'

fint:
  p360:
    defaults:
      casetype:
        tilskudd-fartoy:
          responsibleUnit: 100072
          subArchive: 100007
          keywords:
          archiveCodeType: Fartøy
          initialCaseStatus: B
          contactRole: 5
          documentCategory: 110
          documentStatus: 3
          fileStatus: 1
          fileCategory: 1
          relationType: 1
  adapter:
    endpoints:
      sse: /sse/%s
      status: /status
      response: /response
      providers:
        arkiv: https://beta.felleskomponent.no/administrasjon/arkiv/provider
        kulturminne: https://beta.felleskomponent.no/kultur/kulturminnevern/provider
    organizations: ra.no

  oauth:
    enabled: true
  #    username:
  #    password:
  #    client-id:
  #    client-secret:
  #    access-token-uri:
  #    scope:

security:
  basic:
    enabled: false
